In [4]:
import pandas as pd
import json
import re

In [5]:
er = pd.read_json('event_registry.json')
er

                                                       articles
page                                                          1
pages                                                        40
results       [{'uri': '6770363346', 'lang': 'eng', 'isDupli...
totalResults                                               7908

In [6]:
nested = pd.DataFrame(er.articles.values.tolist()).loc[2, 0]
frame = pd.DataFrame.from_records(nested)
event_registry = frame.drop(labels=['lang', 'isDuplicate', 'time', 'dateTime', 'dateTimePub', 'sim', 
                            'body', 'source', 'authors','image', 'eventUri', 'wgt'], axis=1)
event_registry_slice = event_registry.drop(['uri', 'dataType', 'url', 'sentiment', 'relevance'], axis=1)
event_registry_slice.columns = event_registry_slice.columns.str.replace('date', 'Date')
event_registry_slice.columns = event_registry_slice.columns.str.replace('title', 'Title')
event_registry_slice.Date = pd.to_datetime(event_registry_slice.Date)
event_registry_slice.drop('Date', inplace=True, axis=1)
event_registry_slice

                                                 Title
0    Start A Business, Get An MSc - The University ...
1    Empire BlueCross CEO, president: Innovation st...
2    Report: 76% of manufacturers plan to adopt pri...
3    AI Weekly: AI model training costs on the rise...
4                        Growing the U.S. AI Workforce
..                                                 ...
195  Indian entrepreneur addresses employers confer...
196  Minneapolis Schools' 'Gaggle' Software On Kids...
197  Sensyne Health and OMNY Health Sign Teaming Ag...
198  Show 250 and 12th Year Anniversary Week for Ne...
199  International ZIM Network: SmartMed - Regenera...

[200 rows x 1 columns]

In [7]:
gartner = pd.read_csv('gartner_final.csv')[:200]
gartner

                                                 Title
0    3 Supply Chain Strategies to Drive Purpose-Dri...
1    How to Deliver Relevant Content Across the Tec...
2    6 Key Takeaways from the Gartner Board of Dire...
3     IT Budgets Are Growing. Here's Where the Mone...
4    The Top 8 Cybersecurity Predictions for 2021-2022
..                                                 ...
195  Redesign Recruiting Strategies to Hire Quality...
196  5 Trends From the Gartner Hype Cycle for Suppl...
197  3 Sustainable Retailing Practices for Supply C...
198  Future of Sales 2025: Data-Driven B2B Selling ...
199  Build Organizational Resilience for Today and ...

[200 rows x 1 columns]

In [8]:
df = pd.concat([event_registry_slice, gartner])
df.reset_index(drop=True, inplace=True)
df

                                                 Title
0    Start A Business, Get An MSc - The University ...
1    Empire BlueCross CEO, president: Innovation st...
2    Report: 76% of manufacturers plan to adopt pri...
3    AI Weekly: AI model training costs on the rise...
4                        Growing the U.S. AI Workforce
..                                                 ...
395  Redesign Recruiting Strategies to Hire Quality...
396  5 Trends From the Gartner Hype Cycle for Suppl...
397  3 Sustainable Retailing Practices for Supply C...
398  Future of Sales 2025: Data-Driven B2B Selling ...
399  Build Organizational Resilience for Today and ...

[400 rows x 1 columns]

In [9]:
df.to_csv('gartner_er.csv', index=False)